CMakeLists.txt, rtrlib/lib/utils.c, tools/cli-validator.c
I made some minor changes to compile and run rtrlib under OS X (10.10, to be precise). These will not affect any other systems (Ubuntu, BSD), just some #ifdef statements.
Further a fix for cli-validator.c is also provided, fixing a problem with broken input pipe. Resulting in high cpu load by a quasi zombie cli-validator process.
=> support for OS X, minor tool fix

rtrlib/rtr/rtr.c, rtrlib/rtr_mgr.c
This fixes handling the status callbacks while using more than one ```rtr_mgr_group```. It should call status callbacks in the same manner like using only one ```rtr_mgr_group```.
(Hot)Fixes issue https://github.com/rtrlib/rtrlib/issues/37: deadlock caused by mutex double locking. But I am not sure if the solution is proper.
It adds feature https://github.com/rtrlib/rtrlib/issues/40: Go back to the better-preferred group without waiting for actual established group goes to troubles.
=> Fixes some bugs and improve RTR Manager status callback behavior

README, debian/changelog, debian/control, rtrlib/transport/ssh/ssh_transport.c
The old version did not catch an interrupt signal in the rtr_fsm thread for closing ssh socket.
=> SSH Transport: use new LibSSH API

doxygen/examples/rtr_mgr.c, rtrlib/rtr/rtr.c, rtrlib/rtr/rtr.h, rtrlib/rtr_mgr.c, rtrlib/rtr_mgr.h, tools/cli-validator.c, tools/rtrclient.c
This PR adds error codes that will be returned if a user of the rtrlib uses 
illegal values for the retry/refresh/expire intervals.
Furthermore the user is now able to set the retry interval.
=> Timing params handling

rtrlib/lib/log.c
This fixes a missing ```va_end(argptr)``` in [rtrlib/lib/log.c](https://github.com/rtrlib/rtrlib/blob/master/rtrlib/lib/log.c) found using ```cppcheck```.
=> add missing va_end

rtrlib/rtr/packets.c, rtrlib/rtr_mgr.c, rtrlib/rtr_mgr.h, rtrlib/spki/hashtable/ht-spkitable.c, tools/cli-validator.c, tools/rtrclient.c
This pull request addresses issue #55 
It fixes all warnings on OSX with clang, but on Linux with GCC some _strict aliasing_ warnings remain.
=> reduce warnings

CMakeLists.txt
By default cmake enables C and CXX but we only need a C compiler.
=> [cmake] disable check g++

debian/changelog, debian/rules
- rules: spaces instead of tab
- changelog: missed name/date of entries (reconstructed based on git history)
=> debian pkg build: Fix format of files

rtrlib/rtr/packets.c
const char *a = "...";
sizeof(a); //=> a size of the pointer: 4B @32bit, 8B @64bit
const char a[] = "...";
sizeof(a); //=> a length of the string
=> rtr/packets.c: Fixing sizeof bugs

rtrlib/rtr/packets.c
Hi, developers.
I found maybe a small bug. It used to save new received interval values even from End-Of-Data PDUs with bad session_id. A Session ID check should be performed before processing intervals.
=> packets: save new interval values only after session_id check

README
On some systems the path to the rtrlib.so must be passed to gcc using -L,
else the compiler complains about not finding lrtr.
=> Add simple linking troubleshooting

doxygen/examples/rtr_mgr.c
Also outputs the result of the checked prefix using printf.
Adds the hint that a local rpki-validator is required to open the second TCP transport socket. If the local validator is not present the program may be compiled, it will not run without errors though.
=> doxygen/examples: fixes outdated host and port.

rtrlib/lib/ipv4.h, rtrlib/pfx/pfx.h, rtrlib/rtr/rtr.h
add missing parameter in docstring of function lrtr_ipv4_addr_to_str
=> lib: fix documentation

CMakeLists.txt, doxygen/examples/rtr_mgr.c, rtrlib/transport/ssh/ssh_transport.c
The CMakeLists.txt now checks for SSH 0.5.0 support.
@smlng hinted that the ssh_userauth_publickey_auto function of SSH 0.6.0 is more or less the same as the older 0.5.0 version ssh_userauth_autopubkey.
Still needs testing to confirm same behavior of these functions.
=> rtrlib: LibSSH 0.5.0 support

.codecov.yml, .travis.yml, CMakeLists.txt, README, cmake/modules/AddTest.cmake, rtrlib/rtr/packets.h, scripts/check-coding-files.txt, tests/CMakeLists.txt, tests/unittests/CMakeLists.txt, tests/unittests/rtrlib_unittests.h, tests/unittests/test_packets.c, tests/unittests/test_packets.h, tests/unittests/test_packets_static.c, tests/unittests/test_packets_static.h
this commit adds the first basic unit test to show what is possible
with cmocka. Additionally the build system is adjusted to ease adding
tests.
Fixes #93
=> tests: add first unit test

rtrlib/rtr/packets.c
This is in compliance with RFC6810 Section 5.10 which states that
"If the error is generic (e.g., "Internal Error") and not associated
with the PDU to which it is responding, the Erroneous PDU field MUST
be empty and the Length of Encapsulated PDU field MUST be zero."
=> protocol: do not put the received pdu in the error pdu for internal errors

cmake/modules/FindLibSSH.cmake
The README file mentions that the path to the libssh library can
be specified by defining the LIBSSH_INCLUDE and LIBSSH_LIBRARY variables
but CMAKE wasn't searching in those paths for libssh.
Add those variables to the directory search list for libssh include and
lib files.
=> cmake: search LIBSSH_INCLUDE, LIBSSH_LIBRARY paths for libssh files

rtrlib/rtr_mgr.c, rtrlib/rtr_mgr.h
rtr_mgr_get_spki passes a pointer to a variable that lives in the stack
frame of itself as pointer to pointer to spki_table_get_all.
spki_table_get_all treats this argument as pointer to an array and may
realloc it at will. But since the pointer points to a value on the stack
of rtr_mgr_get_spki it is lost when rtr_mgr_get_spki returns. Thus
leading to a memory leak and causing the function to not actually
returning the result, rendering it useless.
This change technically breaks the api, but since this function was not
functional anyway it should not be a problem.
coverity id: 1420793
=> rtr_mgr: fix memory leak in rtr_mgr_get_spki

rtrlib/rtr/packets.c
In case of a realloc failure during processing of new prefixes and router
keys the arrays where the new data is stored after initial processing are
freed twice. The first time in the processing functions rtr_store_router_key_pdu
or rtr_store_prefix_pdu, depending on the data, and during cleanup in
rtr_sync_receive_and_store_pdus which calls the earlier mentioned ones.
coverity ids: 1420788, 1420796, 1420797
=> packets: fix potential double free vulnerabilities

rtrlib/rtr_mgr.c, rtrlib/rtr_mgr.h
Due to missing validation of the groups_len parameter in rtr_mgr_init
memory allocated for the pfx and spki tables could leak. In the unlikely
case that groups_len is zero no pointer to it would exist after the function
returns. Usually they are passed to rtr_init and stored in the
rtr_sockets, but that does not happen when groups_len is null, since
there is no socket to initialize in that case.
Furthermore this commit fixes a bug in the cleanup which caused a freed
pointer to be returned through config_out, in case of an error
situation.
coverity ids: 1420791 1420783
=> rtr_mgr: Fix memory leak in rtr_mgr_init

rtrlib/rtr_mgr.c
This fixes a bug introduced by 7c6ba5ccf8791a954d31a094bddc9858c381df84. Due to the way cleanup on
error is handled an uninitialized pointer is passed to free if the
execution jumps to err before config->groups is initialized. This
can happen when group_len is zero or when pthread_mutex_init fails.
This commit fixes this by reordering the instructions and returning
early if group_len is zero, because config->groups cannot be initialized
before group_len is validated. The other approach, using different error
labels, would unnecessarily complicate error handling.
coverity id: 1434592
=> rtr_mgr: fix uninitialized pointer read in rtr_mgr_init

.travis.yml, scripts/travis.sh
coverity is a static build analysis tool. Access to the results may be requested on https://scan.coverity.com/projects/rtrlib-rtrlib, but is restricted to project members.
Fixes #62
=> Add coverity scan on branch coverity_scan

rtrlib/lib/ipv4.h, rtrlib/lib/ipv6.h, scripts/check-coding-files.txt
fixes doxygen documentation in `lib/ipv4.h` and `lib/ipv6.h` and also adapt coding style for the latter.
=> lib: fix ip docu

doxygen/mainpage.dox
fixes broken link to pfx table data struct (aka trie) on doxygen mainpage.
=> doc: fix link to trie implementation on doxygen mainpage

CMakeLists.txt, rtrlib/lib/alloc_utils.c, rtrlib/lib/alloc_utils.h, rtrlib/rtr/packets.c, rtrlib/rtr/rtr.c, rtrlib/rtr/rtr.h, rtrlib/rtr_mgr.c, rtrlib/rtr_mgr.h, rtrlib/transport/ssh/ssh_transport.c, rtrlib/transport/tcp/tcp_transport.c, tests/CMakeLists.txt, tests/test_dynamic_groups.c, tests/test_live_validation.c
This uses a linked list instead of an array to store rtr_mgr_groups. It also adds two new functions for the user: rtr_mgr_group_add and rtr_mgr_group_remove. These allow users to add and remove groups while rtr_mgr is running. 
Right now this uses a tommy_list out of convenience. This is a generic doubly linked list. 
This means there are now calls to tommy_* functions in rtr_mgr.c 
Do we want to write our own linked list? Or some kind of wrapper for tommy_list?
Since I am in the middle of writing my masters thesis, it would be good if @ColinBS and @mroethke could pick this up and add necessary changes.  This should include more extensive tests, such as adding/removing groups while rtr_mgr is running and checking whether the changes work as they should there as well.
=> Dynamic adding and removing of rtr_mgr_groups

CMakeLists.txt, doxygen/Doxyfile.in
Building the documentation did not work for out of tree builds because doxygen makes assumptions about the working directory it is run from and our build system did not take that into account when configuring and running the build.
=> Fix doxygen build for out of tree builds

rtrlib/rtr/rtr.h, rtrlib/rtr_mgr.h
Doxygen threw some warings because the parameter names in the
declaration and the doxygen comment did not match in two instances.
=> fix doxygen warnings

.gitignore, redhat/SPECS/librtr.spec
RPM package additions based on setup similar to debian package
Before agreeing to merge, please look at Debian issues in #140 
RPM tested and build clean on CentOS 7 and Fedora 24. It fails on CentOS 6 (libssh is at 0.5.5 which is too old in CentOS 6)
RPM Spec file is designed to work from the SRPM and directly from Git. To build the RPM, use
(from within the rtrlib directory):
rpmbuild --define "_topdir `pwd`/redhat" -ba redhat/SPECS/librtr.spec
Example packages for this PR can be seen at https://ci1.netdef.org/browse/RPKI-RTRLIB-27/artifact
=> redhat: Add rpm Package build infrastructure

rtrlib/rtr/packets.c
Due to a missing cast only the lowest byte of the 4 Byte length of error
text field in the error pdu of the rtrlib protocol was set. The upper 3
Bytes were basically left uninitialized.
This commit also changes the order of the conversion to network byte
order when using the helper function. The footer is now converted before
the header. This eases debugging because the header is still readable
when the footer is converted.
=> packets.c: Fix wrong length of error text in error pdu

rtrlib/lib/alloc_utils.h, rtrlib/rtr_mgr.c, rtrlib/rtr_mgr.h, scripts/check-coding-style.sh
disable check for OPEN_BRACE due to false positive in rtr_mgr.c, error:
```
> check coding style of rtrlib/rtr_mgr.c ...
rtrlib/rtr_mgr.c:724: ERROR:OPEN_BRACE: that open brace { should be on the previous line
```
this line matches `rtr_mgr_for_each_group(...)`, where check patch wants the open `{` on the same line.
=> checkpatch: fix (false positive) warnings and errors

scripts/travis.sh
Due to an error in the travis script the travis build can not fail
because the return value of failed build steps are never propagated to
the build engine.
This commit is expected to fail travis.
=> scripts: fix travis.sh

rtrlib/pfx/trie/trie.c, tests/test_pfx.c
When a non leaf node is deleted one if its childs will takes its place.
The selected child must be the one with the shorter prefix length.
If the one with the longer prefix length is selected the node with the
shorter prefix length will be buried, meaning the search algorithm will
not find it anymore.
Fixes #152
=> trie: fix deletion of non leaf nodes

debian/control, redhat/SPECS/librtr.spec
=> redhat/debian: Dev package needs to require libssh dev package

rtrlib/rtr/packets.c, rtrlib/rtr/packets.h, rtrlib/rtr/rtr.c, rtrlib/rtr/rtr.h, rtrlib/rtr_mgr.c, rtrlib/rtr_mgr.h, tests/unittests/test_packets_static.c
Closes issue #81
Uses same if-statements used in rtr.c
There still are return values for failed checks needed, suggestions are welcome.
=> rtrlib/rtr: add range checks for interval values in packets.c

tests/CMakeLists.txt
Reason: the linker on macOS does not support the `--wrap` option
When running `cmake -DUNIT_TESTING=On .` on macOS I got the following linker error:
```
[...]
[ 95%] Building C object tests/unittests/CMakeFiles/test_packets.dir/test_packets.c.o
[ 96%] Linking C executable test_packets
ld: unknown option: --wrap=rtr_change_socket_state
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [tests/unittests/test_packets] Error 1
make[1]: *** [tests/unittests/CMakeFiles/test_packets.dir/all] Error 2
make: *** [all] Error 2
```
This PR disables cmocka unit testing on macOS, just in case someone tries that.
=> unittests: explicitely disable for Apple macOS

rtrlib/rtr/packets.c, tests/unittests/test_packets_static.c
Due to padding, the pdu_router_key struct was 124 bytes instead of 123 bytes.
Additionally add a unit test for the size of the pdu.
This fixes #163
=> packets: add the packed attribute to the router key pdu.

rtrlib/pfx/pfx.h, rtrlib/pfx/trie/trie-pfx.c, rtrlib/rtr/packets.c, rtrlib/rtr/rtr.c, rtrlib/rtr/rtr.h, rtrlib/spki/hashtable/ht-spkitable.c, rtrlib/spki/spkitable.h, tests/test_ht_spkitable.c, tests/test_pfx.c
If a cache server is unable to perform a incremental update rtrlib resets the socket and deletes all records from that server. Once this is done it starts to recieve new records and then adds them to the tables.
In the time period between the reset and the completion of the add operation the state of the spki and pfx tabe is invalid. Validations in that time period will likely have wrong results.
This implements an atomic reset using a shadow table. It incurs a notable delay in the operations of rtrlibs thread but does not affect validation. Since a cache reset should be rare with properly implemented cache servers this should not be a problem in real world scenarios.
=> Implement atomic reset

rtrlib/rtr/packets.c
In the case SERIAL_NOTIFY there is no break causing it to fall through.
If we receive a malformed SERIAL_NOTIFY with the len field set to the
length of CACHE_RESPONSE this would lead to false positive of the pdu
size check. Resulting in possible out of bound reads.
=> rtr/packets: add missing break in rtr_pdu_check_size

tools/CMakeLists.txt
According to the cmake documentation TARGETS is supposed to be used for
all files that where build by the project. PROGRAMS is for scripts and
such.
=> tools: fix install type for tools

rtrlib/rtr/packets.c, rtrlib/rtr/packets.h, rtrlib/rtr/rtr.c, rtrlib/rtr/rtr.h, rtrlib/rtr_mgr.c, rtrlib/rtr_mgr.h, tests/unittests/test_packets_static.c
The intervals mode symbols do not have a prefix at all right now. This
is problematic because it could easily lead to name collisions when used
in other projects.
Furthermore are the {set,get}_interval_mode functions in the wrong place
they operate on rtr_sockets and should therefore be in rtr.c not in
rtr_mgr.c
While this is a breaking API change I argue that it does not really
matter because the interval mode code has never officially been
released.
=>  rtr: prefix interval mode symbols 

CMakeLists.txt
This description is used at least in the pkg-config file, where it is currently empty. (Feel free to change the description to whatever you like best.)
=> Add description to CMake project() command

CMakeLists.txt
set project description in a way that is compatible with cmake<=3.8
=> cmake: set project description in a way that is compatible with cmake<=3.8

CMakeLists.txt, redhat/SPECS/librtr.spec
I unfortunately noticed two issues with the current release.
1. rpms do not build at all, because we forgot to increase the version number which is used to find the so.
2. Older cmake versions take issue on the LANGUAGES keyword in the project call. 
While I was at it I removed some now unneeded build steps from the spec file.
We should consider releasing this as a bugfix release.
=> Issues with 0.6.0

CMakeLists.txt
including GNUInstallDirs first causes problems with older debian based
distributions
=> cmake: include UseMultiArch before GNUInstallDirs

README
=> README: replace IETF draft by RFC 8210, add C11 compiler requirement

tests/test_ht_spkitable.c
u_int32_t seems to be non standard, while uint32_t is part of the C standard since C99.
I noticed this because the test fails to build on freebsd since the header restructuring.
It relied on transitive includes that are not satisfied anymore on (free)bsd but still are on gnu libc based systems.
=> tests: remove use of u_int32_t

rtrlib/pfx/pfx.h, rtrlib/pfx/pfx_private.h, rtrlib/pfx/trie/trie-pfx.c, rtrlib/pfx/trie/trie-pfx.h, rtrlib/rtr/packets.c, rtrlib/rtr_mgr.c, tests/test_pfx.c, tests/test_pfx_locks.c
This exposes enough of pfxt to make it usable without rtr_mgr.
#190 
@salsh
=> pfx: expose enough of pfxt to make it independently usable

CMakeLists.txt
The GNUInstallDirs CMake module expands CMAKE_INSTALL_LIBDIR to a full
path, which breaks the path munging in CMakeLists.txt.  In particular, a
build on i386 Debian gets the install paths wrong like this:
`debian/tmp/build/librtr0-0.6.1.1/obj-i686-linux-gnu/lib/i386-linux-gnu/librtr.so.0.6.1`
instead of
`debian/tmp/usr/lib/i386-linux-gnu/librtr.so.0.6.1`
=> CMake: fix library installation path

CMakeLists.txt
openbsd lacks librt but includes it's functionality in libc
=> cmake: fix build on openbsd

CMakeLists.txt
GNUInstallDirs and UseMultiArch conflict with each other on newer deb
based distributions because both expand CMAKE_INSTALL_LIBDIR.
Alternative to #196
=> cmake: fix library installation path (again)

README
C11 was only required because of typedef forward declarations, but they
are not used anymore (see PR #188).
=> README: remove c11 requirement

rtrlib/rtrlib.h.cmake
To support inclusion from c++ projects the name mangling must be
disabled for rtrlib symbols, otherwise the linker can't find them.
=> rtrlib: support use in c++ projects

tests/test_pfx.c
The compiler complained about an implicit function declaration because
of a missing include.
Fix #208
=> tests: add missing include in test_pfx

rtrlib/rtr/packets.c
This patch ensures the cleanup code can check whether the shadow tables
have been initialized and only frees them if they are.
Fix #202
=> rtrlib/rtr: Ensure shadow tables are only freed when initialized

redhat/SPECS/librtr.spec
Small fix for the rpm package spec file. Newer tar commands (found in Fedora 29), require the correct placement of the `--exclude options`
Fix required to build RPMs on Fedora 29 and probably other newer RPM based systems
=> redhat: Fix tar command to move options before file

rtrlib/transport/ssh/ssh_transport.c
Currently the ssh transport will never connect successfully because
unless a bindaddr is specified.
This also fixes hostkey verification.
fix #211
=> rtrlib/transport: fix ssh transport

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/enhancement.md, .github/ISSUE_TEMPLATE/feature_request.md
Captions are formatted differently (### vs. ####). This PR formats all captions as third level captions.
=> Github templates: fix inconsistent layout of captions

.travis.yml, scripts/check-exports.sh
This replaces the custom regex based c parser with ctags, this approach should be much more robust.
=> scripts/check-exports: replace custom regex c parser with ctags

rtrlib/rtr/packets.c, rtrlib/rtr/rtr.c
rtr_stop currently has a race condition. It uses a unsynchronized shared
variable. Which value this variable has is therefore undefined when the
thread that rtr_stop tries to kill reads it. The only direct solution is
a explicit memory barrier, but C does not support them until C11, even
there it's optional.
The new approach uses pthread_cancel and carefully selected code regions
where it is safe to exit without freeing resources. The shared variable
is still used but we do not rely on it for timely thread exit anymore.
=> rtrlib/rtr: fix race condition in rtr_stop

CMakeLists.txt, doxygen/examples/rtr_mgr.c, rtrlib/rtr/packets.c, rtrlib/rtr/rtr.c, tests/test_ht_spkitable.c, tests/test_ht_spkitable_locks.c, tests/test_ipaddr.c, tests/test_pfx_locks.c, tools/rpki-rov.c
Disable two compiler warnings that nobody cares for and produced
quite a lot of output (-Wdeclaration-after-statement,
-Waggregate-return) and makes some warnings explicit errors.
It furthermore fixes issues causing errors with the new arguments.
Fix #205
=> Update compiler args in debug mode

tests/unittests/test_packets_static.h
Due to making missing-prototype a error compilation of the test fails
with newer gcc versions
=> tests: add missing prototype

tests/test_dynamic_groups.c, tests/test_live_validation.c
This changes the cache server used by some tests. Because the old one
has been quite unstable in the recent past.
=> tests: change cache server

rtrlib/rtr/packets.c, tests/unittests/test_packets_static.c
This PR improves handling of error pdus in several ways.
- Remove null termination check for the diagnostic error message, the RFC does not demand it and it does not make sense to demand it anyway. ( Fix #234 )
- Print diagnostic message without copying it onto the stack. This fixes a potential security vulnerability in case the maximal pdu length is ever raised.
- Remove duplicated byte order conversion 
Fix #234
=> Improve handling of error pdus

scripts/travis.sh
The patch to master should be displayed for PR runs on travis if the style checker found issues. This does not work right now because of a syntax error.
=> scripts/travis: fix syntax error

scripts/travis.sh
Currently checkpatch checks all c and header files in a PR, including third party code.
This changes the wildcard that generates the patch to inly include files from the rtrlib, tools and tests directories.
=> scripts: check only c files that belong to rtrlib, its tools and testsuite with checkpatch

rtrlib/rtr/rtr.c
Since the sleep calls are not cancellable sections, it would take up to
$retry_interval seconds until an rtr_socket experiencing problems (a
socket waiting for the retry interval to expire) would terminate.
=> rtrlib/rtr: Fix cancellation while waiting for retry interval

tools/CMakeLists.txt
The template.h is generated when building the rtr tools.
The resulting file is now create in the build and not the
source directory. This avoids that template.h shows up in
`git status` and also that someone might commit the file
in to the repo by accident.
Build rtrlib on master:
```
mkdir build
cd build
cmake ../
```
Then run `git status` which will show a new file `tools/template.h` that was
created.
Now do the same with this PR and you'll that this file is not created in `tools/` anymore, 
but in `build/tools/`.
=> tools: generate template.h in build folder

rtrlib/transport/ssh/ssh_transport.c, tests/test_dynamic_groups.c, tests/test_live_validation.c, tools/rpki-rov.c
some warnings are removed by adding some tiny modifications in the code.
Signed-off-by: Philippe Guibert <philippe.guibert@6wind.com>
=> *: fix warnings of compilation with gcc 5.4

redhat/SPECS/librtr.spec
This is a silly fix for the rpmlint error as seen on newer Fedora Versions.
It fixes the `no-changelogname-tag` error which happens if there is new 
recent changelog entry
=> redhat: Add new changelog entry to fix rpmlint changelog error

doxygen/examples/rtr_mgr.c, doxygen/examples/ssh_tr.c, rtrlib/transport/ssh/ssh_transport.c, rtrlib/transport/ssh/ssh_transport.h, rtrlib/transport/tcp/tcp_transport.c, rtrlib/transport/tcp/tcp_transport.h, rtrlib/transport/transport.h, tests/test_dynamic_groups.c, tests/test_live_validation.c, tools/rpki-rov.c
Since the move from pthread_kill to pthread_cancel a rtr_socket could
not be stopped immediately if it was in the tr_open call.
cancelability could not be enabled for that function because it holds
local resources.
This enables cancalability locally for the only blocking call in
tr_tcp_open and tr_ssh_open respectively.
Call `rtr_mgr_stop` shortly after `rtr_mgr_start` and make sure that the connection attempt does not succeed or fail immediately. For instance by dropping the packets via the firewall.
Without this patch `rtr_mgr_stop` hangs until the connection attempts times out.
Fixes #254
=> Fix rtr_stop blocking behavior of tr_open

.gitignore, CMakeLists.txt, README.md, debian/control, redhat/SPECS/librtr.spec, rtrlib/bgpsec/bgpsec.c, rtrlib/bgpsec/bgpsec.h, rtrlib/bgpsec/bgpsec_private.h, rtrlib/bgpsec/bgpsec_utils.c, rtrlib/bgpsec/bgpsec_utils_private.h, rtrlib/config.h.cmake, rtrlib/lib/alloc_utils.c, rtrlib/rtr/packets.c, rtrlib/rtr/rtr.c, rtrlib/rtr_mgr.c, rtrlib/rtr_mgr.h, rtrlib/rtrlib.h.cmake, scripts/check-coding-style.sh, tests/CMakeLists.txt, tests/test_bgpsec.c, tests/unittests/CMakeLists.txt, tests/unittests/test_bgpsec_signing.c, tests/unittests/test_bgpsec_signing.h, tests/unittests/test_bgpsec_utils.c, tests/unittests/test_bgpsec_utils.h, tests/unittests/test_bgpsec_validation.c, tests/unittests/test_bgpsec_validation.h
This PR offers BGPsec validation and signing routines. It extends the current API with functions for
* validating a BGPsec path
* generating a signature for a BGPsec path
* getter functions for BGPsec version and algorithm suites.
The implementation relies on OpenSSL and is compatible with version 1.0 and 1.1. BGPsec functionality is optional. RTRlib can still be build without it. BGPsec features are enabled by default, so no further arguments must be passed to `cmake`. There are however options to disable BGPsec, see the README for more information on this. When building in `Debug` mode, RTRlib will output more information on validation procedures.
```bash
cmake -D CMAKE_BUILD_TYPE=Debug
```
The usage of the API is similar to that of prefix validation. First, RTRlib structures have to be …
=> BGPsec support for RTRlib

rtrlib/rtr/rtr.c
Previously rtr_sockets could not be restarted because their state
remained on SHUTDOWN, which they can, by design, not recover from
themselves.
fix #267
=> rtrlib/rtr_mgr: properly cleanup rtr_sockets on stop

redhat/SPECS/librtr.spec
- Newer Fedora/RedHat changes cmake rpm build to build out of tree
and requires the use of macros for correct locations
See https://fedoraproject.org/wiki/Changes/CMake_to_do_out-of-source_builds
- On newer Fedora, the SOURCES subdirectory isn't created
automatically and needs to be created in the prep phase before
the tar is created
=> redhat: Fix RPM file to work on Fedora 33+ and RedHat 9+

rtrlib/rtr_mgr.c, rtrlib/rtr_mgr.h
rtr_mgr could enter a deadlocked state with multiple socket groups when
a group with at least one group of lower preference comes back online.
This happens because the thread of the group coming back online blocks
on trying to shut down all threads with lower preference while holding
the rtr_mgrs mutex, but a thread that tries to acquire that same mutex
cannot be shut down while doing so.
Since socket threads do not change rtr_mgrs protected structures an
rwlock can be used to allow multiple socket threads to read them while
preventing external calls from changing then concurrently. This allows
the thread that is supposed to shut down to enter code sections where it
can be shut down.
Fix #269
=> rtr_mgr: replace mutex with rwlock

README.md
Fix LIBSSH_ variable names to match expected name from CMakeLists.txt.
=> Fix LIBSSH_ variable names

rtrlib/lib/utils.c
Hurd also uses Mach.
https://www.gnu.org/software/hurd/hurd/porting/guidelines.html
```
#ifdef __MACH__
Some applications put Apple Darwin-specific code inside #ifdef __MACH__ guards. Such guard is clearly not enough, since not only Apple uses Mach as a kernel. This should be replaced by #if defined(__MACH__) && defined(__APPLE__)
```
Try to compile rtrlib on Hurd.
N/A
=> Restrict overmatching MACH ifdef to only trigger on OSX and Mach

tests/test_dynamic_groups.c, tests/test_live_validation.c
The current live tests fail because the cache server used is not running anymore.
This PR changes the name and port of the cache server used for live validation tests and dynamic group tests.
Details steps to test your contribution:
- `make test` all tests should pass now.
=> Update rpki-cache server for testing

tests/test_pfx.c
Motivation
- building with strict aliasing flags failed
- used additional flags shown below
```
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -flto=4 -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_FORTIFY_SOURCE=3 -fdiagnostics-color=always -frecord-gcc-switches")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fstack-clash-protection -march=native -O2 -pipe -U_FORTIFY_SOURCE")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Werror=format-security -Werror=implicit-int -Werror=int-conversion -Wformat")
```
How:
- modify casted variable type in test case to initialized type
- Fixes #287
=> [FIX] Building with strict aliasing

rtrlib/aspa/aspa_private.h, rtrlib/pfx/trie/trie_private.h
- the debug macro needs a function defined inside the rtrlib/lib/log_private.h header which was not included.
=> Fix: including missing header

rtrlib/transport/ssh/ssh_transport.c
#295 reports a bad copy-paste which leads to undefined behavior or at least an invalid error return when the `ssh_socket->config.client_privkey_path` is set to `NULL` and `config->server_hostkey_path` exists. This pull request fixes the incorrect check by changing the condition from `if (!ssh_socket->config.client_privkey_path)` to `if (!ssh_socket->config.server_hostkey_path)`.
n/a
Fixes #295
=> Fix: transport: fix bad copy-paste in `tr_ssh_init`

rtrlib/aspa/aspa.c, rtrlib/aspa/aspa_array/aspa_array.c, rtrlib/bgpsec/bgpsec.c, rtrlib/bgpsec/bgpsec.h, rtrlib/bgpsec/bgpsec_private.h, rtrlib/bgpsec/bgpsec_utils.c, rtrlib/bgpsec/bgpsec_utils_private.h, rtrlib/rtr_mgr.h, rtrlib/transport/ssh/ssh_transport.c, rtrlib/transport/tcp/tcp_transport.c, tests/test_bgpsec.c, tests/unittests/test_bgpsec_signing.c, tests/unittests/test_bgpsec_utils.c, tests/unittests/test_bgpsec_validation.c
#297 reports a missing NULL-check for a memory allocation in `/rtrlib/rtrlib/transport/tcp/tcp_transport.c` which results in undefined behavior / a segmentation fault due to dereferencing a NULL-pointer if the memory allocation failed.
After searching for the memory allocation functions `lrtr_malloc`, `lrtr_calloc`, and `lrtr_realloc` in the source code (i.e. within the `rtrlib/` directory) I found multiple other locations in the code (i.e. in the modules `bgpsec`, `aspa`, and `transport`) where the NULL-check was missing.
This pull request adds the missing NULL-checks, frees previously allocated data if necessary and returns an error code/`NULL` in case the memory allocation failed. In addition, it fixes a memory leak in `tr_ssh_init` which was caused by a premature return when either …
=> Fix: Add missing memory allocation NULL-checks

CMakeLists.txt
Cmake 4 is released and being tested downstream for integration.  Increasing the minimum required cmake version allows to compile rtrlib with cmake 4.
- install cmake 4
- compile
https://bugs.gentoo.org/953446
=> fix build w/ cmake 4
