rtrlib/rtrlib

rtrlib/rtr_mgr.h
+ Retry Interval
+ Switch back to more preferred group
=> doc: update failure handling details in RTR connection manager

doxygen/examples/rtr_mgr.c, rtrlib/lib/ip.c, rtrlib/lib/ip.h, rtrlib/lib/ipv4.c, rtrlib/lib/ipv4.h, rtrlib/lib/ipv6.c, rtrlib/lib/ipv6.h, rtrlib/lib/log.c, rtrlib/lib/log.h, rtrlib/lib/utils.c, rtrlib/lib/utils.h, rtrlib/pfx/lpfst/lpfst-pfx.c, rtrlib/pfx/lpfst/lpfst.c, rtrlib/pfx/lpfst/lpfst.h, rtrlib/pfx/pfx.h, rtrlib/rtr/packets.c, rtrlib/rtr/rtr.c, rtrlib/rtr/rtr.h, rtrlib/rtr_mgr.c, rtrlib/rtr_mgr.h, rtrlib/transport/ssh/ssh_transport.c, rtrlib/transport/tcp/tcp_transport.c, rtrlib/transport/transport.c, tests/test_lpfst.c, tests/test_pfx.c, tests/test_pfx_locks.c, tools/cli-validator.c, tools/rtrclient.c
I am not sure if it is really an improvement.
=> Prefix all in lib/ with lrtr_

rtrlib/rtr/packets.c, rtrlib/rtr/rtr.c, rtrlib/rtr/rtr.h
This PR simplifies the version negotiation mechanism and adds support for the
UNEXPECTED_PROTOCOL_VERSION error code.
=> Changes to live downgrade mechanism

rtrlib/rtr/packets.c, rtrlib/rtr/rtr.c, rtrlib/rtr_mgr.c
=> Revert "Debug"

.travis.yml, scripts/cppcheck.sh
=> Travis cppcheck

rtrlib/rtr/packets.c
This PR also adds null termination checking for the error PDU error message.
=> Bug fix: Some malformed packages could pass the size check

scripts/check-coding-files.txt, tools/cli-validator.c, tools/rtrclient.c
This PR addresses issue #3 and #63 for tools:
- enforced kernel coding style on cli-validator.c and rtrclient.c.
- fixes source file headers to match current template
=> tools coding style compliant

.travis.yml, CMakeLists.txt, cmake/modules/FindGcov.cmake, cmake/modules/FindLcov.cmake, cmake/modules/Findcodecov.cmake
This PR addresses issue #62 and integrates http://codecov.io into travis, see for example: https://codecov.io/github/smlng/rtrlib/rtrlib?ref=9d52582ef95a1eb491c475c95cbbf005b2a3e028
=> add code coverage

scripts/check-coding-files.txt, tests/test_ht_spkitable.c, tests/test_ht_spkitable_locks.c, tests/test_live_validation.c, tests/test_lpfst.c, tests/test_pfx.c, tests/test_pfx_locks.c
- update documentation of all tests
- enforce kernel coding style on all tests
- add all tests to coding style check
=> tests: fix docu and coding style

rtrlib/rtr_mgr.c, rtrlib/rtr_mgr.h, scripts/check-coding-files.txt
- apply coding-style on rtr_mgr.h
- apply coding-style on rtr_mgr.c
- add files to check-coding-files.txt
This PR helps to eventually solve issue #3 ...
=> rtrlib: coding-style for rtr_mgr

rtrlib/rtr/packets.c
In rtr_send_error_pdu() some values where stored in network-byte-order although rtr_send_pdu is responsible for doing this.
=> Bug fix: rtr_send_error_pdu()

rtrlib/lib/ipv4.c, rtrlib/lib/ipv4.h, rtrlib/lib/ipv6.c, rtrlib/lib/ipv6.h, rtrlib/rtr/packets.c, tests/unittests/CMakeLists.txt, tests/unittests/test_packets_static.c
=> Fixes byte order of encapsulated pdu

rtrlib/pfx/trie/trie-pfx.c
fixes issues mentioned in https://github.com/rtrlib/rtrlib/issues/114
=> Fix possible memory leak in pfx_table_append_elem()

CMakeLists.txt, rtrlib/lib/convert_byte_order.c, rtrlib/lib/convert_byte_order.h, rtrlib/lib/ipv4.c, rtrlib/lib/ipv4.h, rtrlib/lib/ipv6.c, rtrlib/lib/ipv6.h, rtrlib/rtr/packets.c, scripts/check-coding-files.txt
fixes #120, compile error was introduced by #106
=> fix byte order conversion on macOS

rtrlib/rtr_mgr.c
follow up on #124 
coverty ids: 1420783, 1420791
=> rtr_mgr: fix resource leaks in rtr_mgr_init

CMakeLists.txt, rtrlib/lib/alloc_utils.c, rtrlib/lib/alloc_utils.h, rtrlib/pfx/trie/trie-pfx.c, rtrlib/pfx/trie/trie.c, rtrlib/rtr/packets.c, rtrlib/rtr_mgr.c, rtrlib/spki/hashtable/ht-spkitable.c, rtrlib/spki/hashtable/tommyds-1.8/tommytypes.h, rtrlib/transport/ssh/ssh_transport.c, rtrlib/transport/tcp/tcp_transport.c, scripts/check-coding-files.txt
This is the malloc wrapper written by @mroethke at the IETF99 Hackathon. This was originally in the dynamic-groups branch, but I've separated it out.
=> Alloc utils

debian/control, debian/librtr-doc.links, debian/rtr-tools.install, debian/rtrclient.install, debian/rules
=> Debian packaging fix

debian/control
=> debian: fix libssh version requirement

rtrlib/rtr/packets.c
this PR makes some simplifications and cleanup of the packet.c file.
=> packets: cleanup

rtrlib/lib/alloc_utils.c, rtrlib/rtr_mgr.c, rtrlib/transport/transport.c
Add missing suppressions to public api functions to silence cppcheck and remove an actually unused function.
=> Cppcheck missing suppressions

CMakeLists.txt, debian/rtr-tools.install, redhat/SPECS/librtr.spec, tools/CMakeLists.txt, tools/rpki-rov.1, tools/rtrclient.1
This kind of depends on #169 because it assumes the name change is already made.
Fix #145
=> tools: add man pages

tests/test_dynamic_groups.c
Without a timeout the test will hang indefinitely if for whatever reason
the connection to the cache server can not be established.
=> tests: add connect timeout to test_dynamic_groups

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/enhancement.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
Makes structuring of issues and pull requests easier.
=> add Github templates for issues and PRs

rtrlib/rtr_mgr.c
Fix check ensuring uniqueness of group preferences
=> rtrlib/rtr_mgr: fix check ensuring uniqueness of group preferences

.travis.yml, rtrlib/lib/alloc_utils.c, rtrlib/pfx/trie/trie-pfx.c, rtrlib/rtr/packets.c, rtrlib/rtr_mgr.c, rtrlib/transport/tcp/tcp_transport.c, rtrlib/transport/transport.c, scripts/check-exports.sh
Use the ubuntu 16.04 image instead of 14.04 on travis.
=> travis: use ubuntu 16.04

tools/rpki-rov.c
The input validation was insufficient which could lead to buffer
overflows, uninitialized jumps and undefined behaviour.
coverity: 1477248
Use rpki-rov and enter a line like "999999999999 e f", it will happily accept and try to validate it.
=> tools/rpki-rov: improve input validation

rtrlib/rtr_mgr.c, scripts/check-coding-style.sh, scripts/checkpatch.pl, scripts/travis.sh, tests/test_ht_spkitable.c, tests/test_ht_spkitable_locks.c, tests/test_pfx.c, tools/rtrclient.c
- Update checkpatch
- fix issues found by new checkpatch
- Check the diff in addition to the whitelisted files with checkpatch
This will not (yet) fail the build because it could cause problems with changes files not conforming to our standards.
- Ensure all build steps are executed even if some fail
=> Travis ci updates

scripts/check-coding-style.sh, scripts/travis.sh, tools/rtrclient.c
Increase Line length to 120 characters and fix remaining warnings in rtrclient based on it.
=> Increase Line length to 120 characters

rtrlib/transport/tcp/tcp_transport.c
In case `tr_tcp_open` receives an _EAI_SYSTEM_ error code, `gai_strerror` would only print "Unknown error". `strerror` will then print a more detailed error string, e.g. "Resource temporarily unavailable". This error string is more useful for debugging purposes.
=> rtrlib/transport/tcp: add extended errno output

README.md
This PR adds badges to the README.md and a ref to the contributing guidelines.
https://github.com/waehlisch/rtrlib/blob/master/README.md
=> add badges to README.md and ref to CONTRIBUTING

doxygen/examples/rtr_mgr.c, rtrlib/aspa/aspa_private.h
- the example inside the doxygen folder still used the old api
=> Updating the Doxygen Example
